/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package net.localizethat.gui.dialogs;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.localizethat.Main;

/**
 * An about box
 * @author rpalomares
 */
public class AboutDialog extends javax.swing.JDialog {
    private static final String website = "http://www.localizethat.net/";
    private final URI productHomeUri;

    /** Creates new form AboutDialog
     * @throws java.net.URISyntaxException */
    public AboutDialog() throws URISyntaxException {
        super(Main.mainWindow, "", true);
        productHomeUri = new URI(website);
        initComponents();
        // setTitle("MozillaTranslator " + Kernel.settings.getString("system.version", "(Unknown version)"));
    }

    private void openWebsite() {
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(productHomeUri);
            } catch (IOException ex) {
                Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JTabbedPane aboutTabbedPane = new javax.swing.JTabbedPane();
        javax.swing.JPanel generalPanel = new javax.swing.JPanel();
        productNameLabel = new javax.swing.JLabel();
        javax.swing.JTextArea generalArea = new javax.swing.JTextArea();
        versionNumberLabel = new javax.swing.JLabel();
        totalMemLabel = new javax.swing.JLabel();
        freeMemLabel = new javax.swing.JLabel();
        maxMemLabel = new javax.swing.JLabel();
        javax.swing.JPanel licencePanel = new javax.swing.JPanel();
        licenceArea = new javax.swing.JTextArea();
        javax.swing.JPanel addressPanel = new javax.swing.JPanel();
        wommLogo = new javax.swing.JLabel();
        websiteLinkButton = new javax.swing.JButton();
        okButtonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setTitle("About LocalizeThat!");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        generalPanel.setLayout(new java.awt.GridBagLayout());

        productNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        productNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productNameLabel.setText("LocalizeThat!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 5);
        generalPanel.add(productNameLabel, gridBagConstraints);

        generalArea.setEditable(false);
        generalArea.setBackground(new java.awt.Color(184, 207, 229));
        generalArea.setColumns(15);
        generalArea.setRows(10);
        generalArea.setText("\nDesktop localization tool for Mozilla\nThe replacement for MozillaTranslator");
        generalArea.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        generalPanel.add(generalArea, gridBagConstraints);

        versionNumberLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        versionNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionNumberLabel.setText("v0.1");
        versionNumberLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        generalPanel.add(versionNumberLabel, gridBagConstraints);

        totalMemLabel.setText("Total memory: 123456 KB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        generalPanel.add(totalMemLabel, gridBagConstraints);

        freeMemLabel.setText("Free memory: 123456 KB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        generalPanel.add(freeMemLabel, gridBagConstraints);

        maxMemLabel.setText("Max memory: 123456 KB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        generalPanel.add(maxMemLabel, gridBagConstraints);

        aboutTabbedPane.addTab("General", null, generalPanel, "");

        licencePanel.setLayout(new java.awt.BorderLayout());

        licenceArea.setEditable(false);
        licenceArea.setBackground(new java.awt.Color(184, 207, 229));
        licenceArea.setColumns(15);
        licenceArea.setRows(12);
        licenceArea.setText("\nLocalizeThat! is released under MPL 2.0\nhttp://mozilla.org/MPL/2.0/\n\nGraphic art taken or derived from Tango Icon Theme,\nand from Open Clip Art:\n(http://openclipart.org/detail/94723/database-symbol-by-rg1024)");
        licenceArea.setOpaque(false);
        licencePanel.add(licenceArea, java.awt.BorderLayout.CENTER);

        aboutTabbedPane.addTab("License", null, licencePanel, "");

        addressPanel.setLayout(new java.awt.BorderLayout());

        wommLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wommLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/localizethat/resources/womm.png"))); // NOI18N
        addressPanel.add(wommLogo, java.awt.BorderLayout.PAGE_START);

        websiteLinkButton.setBackground(java.awt.Color.white);
        websiteLinkButton.setForeground(java.awt.Color.blue);
        websiteLinkButton.setText("http://www.localizethat.net/");
        websiteLinkButton.setBorder(null);
        websiteLinkButton.setBorderPainted(false);
        websiteLinkButton.setOpaque(false);
        websiteLinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteLinkButtonActionPerformed(evt);
            }
        });
        addressPanel.add(websiteLinkButton, java.awt.BorderLayout.CENTER);

        aboutTabbedPane.addTab("Quality Assurance", null, addressPanel, "");

        getContentPane().add(aboutTabbedPane, java.awt.BorderLayout.NORTH);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(60, 29));
        okButton.setMinimumSize(new java.awt.Dimension(60, 29));
        okButton.setPreferredSize(new java.awt.Dimension(60, 29));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okButtonPanel.add(okButton);

        getContentPane().add(okButtonPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        maxMemLabel.setText("Max. memory: " + (Runtime.getRuntime().maxMemory() / 1024) + " KB");
        totalMemLabel.setText("Total memory: " + (Runtime.getRuntime().totalMemory() / 1024) + " KB");
        freeMemLabel.setText("Free memory: " + (Runtime.getRuntime().freeMemory() / 1024) + " KB");
    }//GEN-LAST:event_formWindowOpened

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void websiteLinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteLinkButtonActionPerformed
        openWebsite();
    }//GEN-LAST:event_websiteLinkButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel freeMemLabel;
    private javax.swing.JTextArea licenceArea;
    private javax.swing.JLabel maxMemLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okButtonPanel;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel totalMemLabel;
    private javax.swing.JLabel versionNumberLabel;
    private javax.swing.JButton websiteLinkButton;
    private javax.swing.JLabel wommLogo;
    // End of variables declaration//GEN-END:variables
}
