/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package net.localizethat.gui.dialogs;

import java.beans.Beans;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import net.localizethat.Main;
import net.localizethat.model.L10n;
import net.localizethat.model.LocalePath;
import net.localizethat.model.Product;
import net.localizethat.util.gui.ModalDialog;
import net.localizethat.util.gui.ModalDialogComponent;

/**
 *
 * @author rpalomares
 */
public class ChooseTreePanel extends javax.swing.JPanel implements ModalDialogComponent {
    EntityManagerFactory emf;
    ModalDialog md;

    /**
     * Creates new form ChooseTreePanel
     */
    public ChooseTreePanel() {
        super();
        emf = Main.emf;
        // The following code is executed inside initComponents()
        // entityManager = emf.createEntityManager();

        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        refreshL10nList();
        refreshProductList();
        refreshOrigPathList();
    }

    private void refreshL10nList() {
        TypedQuery<L10n> l10nQuery = entityManager.createNamedQuery("L10n.findAll",
                L10n.class);
        l10nListModel.clearAll();
        l10nListModel.addAll(l10nQuery.getResultList());
    }

    private void refreshProductList() {
        TypedQuery<Product> productQuery = entityManager.createNamedQuery("Product.findAll",
                Product.class);
        productListModel.clearAll();
        productListModel.addAll(productQuery.getResultList());
    }

    private void refreshOrigPathList() {
        TypedQuery<LocalePath> localePathQuery = entityManager.createNamedQuery(
                "LocalePath.findOriginals", LocalePath.class);
        localePathListModel.clearAll();
        localePathListModel.addAll(localePathQuery.getResultList());
    }

    @Override
    public void setModalDialogReference(ModalDialog md) {
        this.md = md;
    }

    public L10n getTargetL10n() {
        return l10nListModel.getSelectedTypedItem();
    }

    public Product getSelectedProduct() {
        if (this.productPathsRadio.isSelected()) {
            return productListModel.getSelectedTypedItem();
        } else {
            return null;
        }
    }

    public List<LocalePath> getSelectedPaths() {
        if (this.selectedPathsRadio.isSelected()) {
            return this.pathsList.getSelectedValuesList();
        } else {
            return localePathListModel.getAll();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = emf.createEntityManager();
        treeContentsRadioGroup = new javax.swing.ButtonGroup();
        l10nListModel = new net.localizethat.gui.models.ListComboBoxGenericModel<L10n>();
        productListModel = new net.localizethat.gui.models.ListComboBoxGenericModel<Product>();
        localePathListModel = new net.localizethat.gui.models.ListComboBoxGenericModel<LocalePath>();
        targetLocaleLabel = new javax.swing.JLabel();
        targetLocaleCombo = new javax.swing.JComboBox();
        treeContentLabel = new javax.swing.JLabel();
        allPathsRadio = new javax.swing.JRadioButton();
        productPathsRadio = new javax.swing.JRadioButton();
        productCombo = new javax.swing.JComboBox();
        selectedPathsRadio = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pathsList = new javax.swing.JList();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        targetLocaleLabel.setText("Choose target locale:");

        targetLocaleCombo.setModel(l10nListModel);

        treeContentLabel.setText("Choose tree contents:");

        treeContentsRadioGroup.add(allPathsRadio);
        allPathsRadio.setText("All original paths");
        allPathsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allPathsRadioActionPerformed(evt);
            }
        });

        treeContentsRadioGroup.add(productPathsRadio);
        productPathsRadio.setText("Paths for product:");
        productPathsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPathsRadioActionPerformed(evt);
            }
        });

        productCombo.setModel(productListModel);
        productCombo.setEnabled(false);

        treeContentsRadioGroup.add(selectedPathsRadio);
        selectedPathsRadio.setText("Selected paths:");
        selectedPathsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedPathsRadioActionPerformed(evt);
            }
        });

        pathsList.setModel(localePathListModel);
        pathsList.setEnabled(false);
        jScrollPane1.setViewportView(pathsList);

        okButton.setText("OK");
        okButton.setToolTipText("");
        okButton.setMaximumSize(new java.awt.Dimension(94, 25));
        okButton.setMinimumSize(new java.awt.Dimension(94, 25));
        okButton.setPreferredSize(new java.awt.Dimension(94, 25));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(94, 25));
        cancelButton.setMinimumSize(new java.awt.Dimension(94, 25));
        cancelButton.setPreferredSize(new java.awt.Dimension(94, 25));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(targetLocaleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(targetLocaleCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(treeContentLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productPathsRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(allPathsRadio)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectedPathsRadio)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetLocaleLabel)
                    .addComponent(targetLocaleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(treeContentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allPathsRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productPathsRadio)
                    .addComponent(productCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedPathsRadio)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        md.setModalDialogResult(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        boolean validL10n = (l10nListModel.getSelectedIndex() != -1);
        boolean validProduct = (productPathsRadio.isSelected() && productListModel.getSelectedIndex() != -1);
        boolean validSelectedPaths = (selectedPathsRadio.isSelected() && pathsList.getSelectedIndex() != -1);
        if (validL10n && (allPathsRadio.isSelected() || validProduct || validSelectedPaths)) {
            md.setModalDialogResult(true);            
        } else {
            JOptionPane.showMessageDialog(this, "Please, select a locale and a valid path set",
                    "Error: required data missing", JOptionPane.ERROR_MESSAGE);
            if (!validL10n) {
                targetLocaleCombo.requestFocus();
            } else if (!validProduct) {
                productCombo.requestFocus();
            } else {
                pathsList.requestFocus();
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void allPathsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allPathsRadioActionPerformed
        productCombo.setEnabled(false);
        pathsList.setEnabled(false);
    }//GEN-LAST:event_allPathsRadioActionPerformed

    private void productPathsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPathsRadioActionPerformed
        productCombo.setEnabled(true);
        pathsList.setEnabled(false);
    }//GEN-LAST:event_productPathsRadioActionPerformed

    private void selectedPathsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedPathsRadioActionPerformed
        productCombo.setEnabled(false);
        pathsList.setEnabled(true);
    }//GEN-LAST:event_selectedPathsRadioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allPathsRadio;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JScrollPane jScrollPane1;
    private net.localizethat.gui.models.ListComboBoxGenericModel<L10n> l10nListModel;
    private net.localizethat.gui.models.ListComboBoxGenericModel<LocalePath> localePathListModel;
    private javax.swing.JButton okButton;
    private javax.swing.JList pathsList;
    private javax.swing.JComboBox productCombo;
    private net.localizethat.gui.models.ListComboBoxGenericModel<Product> productListModel;
    private javax.swing.JRadioButton productPathsRadio;
    private javax.swing.JRadioButton selectedPathsRadio;
    private javax.swing.JComboBox targetLocaleCombo;
    private javax.swing.JLabel targetLocaleLabel;
    private javax.swing.JLabel treeContentLabel;
    private javax.swing.ButtonGroup treeContentsRadioGroup;
    // End of variables declaration//GEN-END:variables

}
