@startuml
package net.localizethat.actions {
    class EditContentAction
    class ExportProductsAction
    class GlossaryManagerAction
    class L10nManagerAction
    class ProductManagerAction
    note "Otras acciones asociadas a opciones de menú" as N1
}

package net.localizethat.gui {
    package components {
        class ContentEditionPanel
        class ContentListEditPanel
        class ContentListTable
        class EllipsisUnicodeCharKeyAdapter
        note bottom: Permite obtener el carácter elipsis rápidamente
    }
    package dialogs {
        class ChooseTreePanel
        class ImportCSVGlossaryDialog
        class PreferencesDialog
        note "Otras clases de diálogo y apoyo" as N2
    }
    package models {
        class ContentListTableModel
        class GlosEntryTableModel
        class GlosTranslationTableModel
        class GlossaryTableModel
        class L10nTableModel
        class ListComboBoxGenericModel
        note "Otras clases de modelo de tablas y apoyo" as N3
    }
    package renderers {
        class SelectableListItem
    }
    package tabpanels {
        abstract class AbstractTabPanel
        class EditContentPanel
        class ExportProductPanel
        class GlossaryGuiManager
        class ImportProductPanel
        class L10nGuiManager
        class ProductManager
        class UpdateProductPanel
        AbstractTabPanel <|- EditContentPanel
        AbstractTabPanel <|- ExportProductPanel
        AbstractTabPanel <|- GlossaryGuiManager
        AbstractTabPanel <|-- ImportProductPanel
        AbstractTabPanel <|-- L10nGuiManager
        AbstractTabPanel <|-- ProductManager
        AbstractTabPanel <|-- UpdateProductPanel
    }
    class MainWindow
}
package net.localizethat.io {
    package parsers {
        class DTDReadHelper
        class PropertiesReadHelper
        interface ReadHelper
        ReadHelper <|.. DTDReadHelper
        ReadHelper <|.. PropertiesReadHelper
    }
    class DtdFileAccess
    interface ParseableFileAccess
    class PropertiesFileAccess
    ParseableFileAccess <|.. DtdFileAccess
    ParseableFileAccess <|.. PropertiesFileAccess
}
package net.localizethat.model {
    package jpa {
        class JPAHelperBundle
        class LocaleContainerJPAHelper
        class LocaleFileJPAHelper
        class LocaleContentJPAHelper
        JPAHelperBundle *-- LocaleContainerJPAHelper
        JPAHelperBundle *-- LocaleFileJPAHelper
        JPAHelperBundle *-- LocaleContentJPAHelper
        note "Los scripts de autoactualización SQL están aquí" as N4
    }
    class DtdFile
    interface EditableLocaleContent
    class Glossary
    class ImageFile
    class L10n
    interface LocaleContent
    class LocaleContainer
    class LTContent
    class LocalePath
    class Product
    class PropertiesFile
    note "Resto de clases del modelo" as N5
}
package net.localizethat.resources {
    note "Imágenes y otros recursos estáticos" as N6
}
package net.localizethat.system {
    class AppSettings
    class DBChecker
    class SQLScriptRunner
    DBChecker -- SQLScriptRunner
}
package net.localizethat.tasks {
    class CSVImporterWorker
    class CheckGlossaryWorker
    class ExportProductWorker
    class ImportProductWorker
    class SavePreferencesWorker
    class UpdateProductWorker
}
package net.localizethat.util {
    package gui {
        class JPathField
        class JStatusBar
        class ModalDialog
        note "Otras clases e interfaces de utilidad relacionadas con GUI" as N7
    }
    class BlobChecker
    class DateToStringConverter
    class VersionObject
    note "Otras clases de utilidad" as N8
}
class Main
@enduml